/** Demand-driven instanced WebGPU rectangles, shared Canvas2D fallback and hit tests. */
export class SceneRenderer{
 constructor(canvas){this.canvas=canvas;this.items=[];this.mode='Canvas';this.device=null;this.context=null;this.frame=0;this.destroyed=false;this.hitGrid=new Map();this.resizeObserver=new ResizeObserver(()=>this.draw());this.resizeObserver.observe(canvas)}
 fallback(reason){if(this.destroyed)return;this.buffer?.destroy();this.params?.destroy();let oldDevice=this.device;this.device=null;this.buffer=null;this.params=null;if(this.context){this.resizeObserver.disconnect();let fresh=this.canvas.cloneNode(false);this.canvas.replaceWith(fresh);this.canvas=fresh;this.context=null;this.resizeObserver.observe(fresh)}this.ctx=this.canvas.getContext('2d');this.mode='Canvas';oldDevice?.destroy();this.onModeChange?.(this.mode,this.canvas);if(reason)this.onError?.(reason);this.draw()}
 async init(){if(navigator.gpu){try{const adapter=await navigator.gpu.requestAdapter();if(this.destroyed)return this.mode;if(adapter){let device=await adapter.requestDevice();if(this.destroyed){device.destroy();return this.mode}this.device=device;this.format=navigator.gpu.getPreferredCanvasFormat();const shader=device.createShaderModule({code:`struct Instance {rect:vec4f,color:vec4f}; struct Params {size:vec2f,pad:vec2f}; @group(0) @binding(0) var<storage,read> instances:array<Instance>; @group(0) @binding(1) var<uniform> params:Params; struct Out{@builtin(position) position:vec4f,@location(0) color:vec4f}; @vertex fn vs(@builtin(vertex_index) v:u32,@builtin(instance_index) i:u32)->Out{var points=array<vec2f,6>(vec2f(0,0),vec2f(1,0),vec2f(0,1),vec2f(0,1),vec2f(1,0),vec2f(1,1));let p=instances[i].rect.xy+points[v]*instances[i].rect.zw;var out:Out;out.position=vec4f(p.x/params.size.x*2.-1.,1.-p.y/params.size.y*2.,0.,1.);out.color=instances[i].color;return out;} @fragment fn fs(in:Out)->@location(0) vec4f{return in.color;}`});this.pipeline=await device.createRenderPipelineAsync({layout:'auto',vertex:{module:shader,entryPoint:'vs'},fragment:{module:shader,entryPoint:'fs',targets:[{format:this.format,blend:{color:{srcFactor:'src-alpha',dstFactor:'one-minus-src-alpha'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha'}}}]},primitive:{topology:'triangle-list'}});if(this.destroyed){device.destroy();return this.mode}this.context=this.canvas.getContext('webgpu');if(!this.context)throw Error('WebGPU canvas unavailable');this.context.configure({device,format:this.format,alphaMode:'premultiplied'});this.params=device.createBuffer({size:16,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});this.mode='WebGPU';device.lost.then(info=>{if(!this.destroyed&&this.device===device)this.fallback(info.message||'Graphics device lost')});}}catch(e){this.fallback(e.message)}}if(!this.context&&!this.destroyed)this.ctx=this.canvas.getContext('2d');this.draw();return this.mode}
 set(items){this.items=items;this.hitGrid.clear();for(let item of items)if(item.id){for(let y=Math.floor(item.y/64);y<=Math.floor((item.y+item.h)/64);y++){let row=this.hitGrid.get(y)||[];row.push(item);this.hitGrid.set(y,row)}}this.draw()}
 hit(x,y){return(this.hitGrid.get(Math.floor(y/64))||[]).findLast(r=>x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h)}
 draw(){if(this.destroyed)return;cancelAnimationFrame(this.frame);this.frame=requestAnimationFrame(()=>this.render())}
 render(){if(this.destroyed)return;let {width,height}=this.canvas.getBoundingClientRect();if(!width||!height)return;const dpr=Math.min(devicePixelRatio||1,2);let w=Math.round(width*dpr),h=Math.round(height*dpr);if(this.canvas.width!==w)this.canvas.width=w;if(this.canvas.height!==h)this.canvas.height=h;let items=this.items.filter(i=>i.x+i.w>=0&&i.y+i.h>=0&&i.x<=width&&i.y<=height);if(this.device&&this.context){try{const floats=new Float32Array(Math.max(1,items.length)*8);items.forEach((r,i)=>floats.set([r.x,r.y,r.w,r.h,...r.color],i*8));let size=floats.byteLength;if(!this.buffer||this.capacity<size){this.buffer?.destroy();this.capacity=2**Math.ceil(Math.log2(Math.max(size,256)));this.buffer=this.device.createBuffer({size:this.capacity,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});this.bindGroup=this.device.createBindGroup({layout:this.pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.buffer}},{binding:1,resource:{buffer:this.params}}]})}this.device.queue.writeBuffer(this.buffer,0,floats);this.device.queue.writeBuffer(this.params,0,new Float32Array([width,height,0,0]));let encoder=this.device.createCommandEncoder(),pass=encoder.beginRenderPass({colorAttachments:[{view:this.context.getCurrentTexture().createView(),clearValue:{r:0,g:0,b:0,a:0},loadOp:'clear',storeOp:'store'}]});pass.setPipeline(this.pipeline);pass.setBindGroup(0,this.bindGroup);pass.draw(6,items.length);pass.end();this.device.queue.submit([encoder.finish()]);}catch(e){this.fallback(e.message)}}else if(this.ctx){let c=this.ctx;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,width,height);for(let r of items){c.fillStyle=`rgba(${r.color.slice(0,3).map(n=>Math.round(n*255)).join(',')},${r.color[3]})`;c.beginPath();c.roundRect(r.x,r.y,r.w,r.h,r.radius||0);c.fill()}}}
 destroy(){this.destroyed=true;this.resizeObserver.disconnect();cancelAnimationFrame(this.frame);this.buffer?.destroy();this.params?.destroy();this.device?.destroy()}
}
