import {Replica} from './core.js';
export function seedWorkspace(name='My workspace'){
 const r=new Replica('seed');let seq=0;r.next=()=>`${String(++seq).padStart(16,'0')}:seed`;const p=(id,title,icon,kind='document',extra={})=>r.create('page',{title,icon,kind,order:r.entities.size,parent:null,...extra},id);
 p('home','Workspace home','🏡','home',{favorite:true,cover:'green'});p('projects','Projects','◈','database',{favorite:true,description:'A little structure for your next big thing.',cover:'blue'});p('wiki','Team wiki','📚','document',{favorite:true,description:'What we know. How we work. All in one place.'});p('notes','Meeting notes','📝','document');p('ideas','Ideas & inspiration','💡','document');p('welcome','Getting started','👋','document');
 const block=(page,style,text,extra={})=>r.create('block',{page,style,text,order:r.entities.size*100,...extra});
 block('home','callout','Good work starts with a little clarity. This is your space to think, plan, and build something great.',{emoji:'✨'});
 block('home','heading2','Make room for your best work');block('home','paragraph','Keep your team in sync, your projects moving, and your ideas close. Everything here is editable — make yourself at home.');
 block('home','heading2','This week’s focus');block('home','todo','Bring the team together for our weekly kickoff',{checked:true});block('home','todo','Refine the next release with the product team');block('home','todo','Leave a little space for something unexpected');
 block('wiki','callout','A shared place for the things that make us, us.',{emoji:'📌'});block('wiki','heading2','Start here');block('wiki','paragraph','We build thoughtfully, communicate openly, and give good ideas the room they need. Our wiki is a living document — add what you learn along the way.');block('wiki','heading2','Our working principles');block('wiki','bullet','Make things clear. Write it down, keep it simple, and share early.');block('wiki','bullet','Own the outcome. Good work is a team sport.');block('wiki','bullet','Stay curious. Ask why, try something new, and learn together.');block('wiki','toggle','How we make decisions',{detail:'Write a short proposal, invite the right perspectives, agree on a next step, and record the decision here.'});block('wiki','quote','Great teams are built one thoughtful conversation at a time.');
 block('notes','heading2','Weekly team sync');block('notes','paragraph','September 14, 2026 · 30 minutes');block('notes','heading3','Agenda');block('notes','number','Celebrate a win from last week');block('notes','number','Review project progress and blockers');block('notes','number','Agree on the most important thing for this week');block('notes','heading3','Action items');block('notes','todo','Add your next step here');
 block('ideas','heading2','A home for your next idea');block('ideas','paragraph','Small observations, big possibilities, and everything in between.');block('ideas','callout','Try typing / in a new block to add a heading, checklist, image, or database.',{emoji:'💡'});
 block('welcome','heading2','Welcome to Folio');block('welcome','paragraph','Your workspace brings documents, knowledge, and projects together. Click any text to start writing.');block('welcome','number','Create a page with the + button in your sidebar.');block('welcome','number','Type / to explore blocks. Drag the six-dot handle to rearrange them.');block('welcome','number','Open Projects to switch between table, board, calendar, gallery, and timeline views.');block('welcome','number','Use Share to create an invitation link and collaborate in a shared workspace.');block('welcome','number','Your edits save automatically. Export your workspace anytime from Settings.');
 const properties=[{id:'status',name:'Status',type:'status',options:['Not started','In progress','In review','Done']},{id:'owner',name:'Owner',type:'person'},{id:'date',name:'Due date',type:'date'},{id:'priority',name:'Priority',type:'select',options:['High','Medium','Low']},{id:'tags',name:'Tags',type:'multi',options:['Design','Product','Engineering','Marketing']},{id:'progress',name:'Progress',type:'number'}];r.set('projects','properties',properties);
 const tasks=[['Website refresh','In progress','Alex Morgan','2026-09-18','High',['Design'],65,'🎨'],['Customer discovery','In progress','Jordan Lee','2026-09-16','High',['Product'],40,'🔎'],['Design system 2.0','In review','Sam Rivera','2026-09-22','Medium',['Design'],85,'✳️'],['Launch campaign','Not started','Taylor Chen','2026-09-28','Medium',['Marketing'],10,'🚀'],['Mobile experience','Not started','Alex Morgan','2026-09-25','High',['Engineering'],20,'📱'],['Team onboarding','Done','Jordan Lee','2026-09-11','Low',['Product'],100,'🌱']];
 tasks.forEach(([title,status,owner,date,priority,tags,progress,icon],i)=>{let id=r.create('record',{title,db:'projects',icon,order:i*100});for(let[k,v]of Object.entries({status,owner,date,priority,tags,progress}))r.set(id,'prop:'+k,v);block(id,'heading2','Overview');block(id,'paragraph','A thoughtful approach, clear next steps, and a little room to explore. Add context, notes, and decisions here.');block(id,'todo','Define the outcome');block(id,'todo','Share the first draft');});
 ['Table','Board','Calendar','Gallery','Timeline','Chart','List'].forEach((n,i)=>r.create('view',{title:n,db:'projects',layout:n.toLowerCase(),order:i*100,filters:[],sort:[],group:'status'}));return r.export();
}
