import {Replica} from './core.js';
export class WorkspaceSync{
 constructor(onStatus=()=>{}){this.replica=new Replica();this.onStatus=onStatus;this.pending=new Map();this.unpersisted=new Map();this.cursor=0;this.busy=false;this.persistChain=Promise.resolve();this.workspace=null;this.db=null;this.ready=false;this.stopped=false;this.replica.onLocal(op=>{this.pending.set(op.id,op);this.unpersisted.set(op.id,op);this.onStatus('Saving…');this.queuePersistence();clearTimeout(this.flushTimer);this.flushTimer=setTimeout(()=>this.flush(),350)})}
 queuePersistence(){this.persistChain=this.persistChain.catch(()=>{}).then(async()=>{for(let [id,op]of this.unpersisted){await this.writeLocal(op);this.unpersisted.delete(id)}});this.persistChain.catch(()=>this.onStatus('Device storage error — keep this tab open'));return this.persistChain}
 async open(){let args=new URLSearchParams(location.search);try{let outer=new URL(parent.location.href);for(let k of['workspace','invite'])if(outer.searchParams.has(k))args.set(k,outer.searchParams.get(k))}catch{}
 let q=new URLSearchParams();for(let k of['workspace','invite'])if(args.has(k))q.set(k,args.get(k));let offline=false;try{this.session=await this.api('session?'+q);localStorage.setItem('folio-session',JSON.stringify(this.session))}catch(e){if(e.status||args.has('invite'))throw e;let cached=localStorage.getItem('folio-session');if(!cached)throw e;this.session=JSON.parse(cached);if(args.has('workspace')&&args.get('workspace')!==this.session.workspace.id)throw e;offline=true}this.workspace=this.session.workspace.id;
 this.db=await new Promise((resolve,reject)=>{const r=indexedDB.open('folio-'+this.workspace,1);r.onupgradeneeded=()=>{r.result.createObjectStore('operations',{keyPath:'id'});r.result.createObjectStore('outbox',{keyPath:'id'});r.result.createObjectStore('meta')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
 const snapshot=await new Promise((resolve,reject)=>{let tx=this.db.transaction(['operations','outbox','meta'],'readonly'),ops=tx.objectStore('operations').getAll(),pending=tx.objectStore('outbox').getAll(),cursor=tx.objectStore('meta').get('cursor');tx.oncomplete=()=>resolve({operations:ops.result,pending:pending.result,cursor:cursor.result||0});tx.onerror=tx.onabort=()=>reject(tx.error)});
 this.replica.import(snapshot.operations);snapshot.pending.forEach(op=>this.pending.set(op.id,op));this.cursor=snapshot.cursor;
 if(!offline){try{await this.pull()}catch(e){if(!snapshot.operations.length||e.status===401||e.status===403)throw e;offline=true}}
 this.ready=true;this.onStatus(offline?'Offline · cached workspace, access pending':this.pending.size?'Saving…':'All changes saved');this.flush();this.tick();window.addEventListener('online',()=>this.flush());return this.session;
 }
 async api(path,options={}){let sep=path.includes('?')?'&':'?';let response=await fetch('/api/folio/'+path+(this.workspace?sep+'workspace='+encodeURIComponent(this.workspace):''),{...options,headers:{...(options.body&&typeof options.body==='string'?{'content-type':'application/json'}:{}),...options.headers}});let v;try{v=await response.json()}catch{throw new Error('The workspace could not be reached. Please try again.')};if(!response.ok){let e=new Error(v.error||'Request failed');e.status=response.status;e.signin=v.signin;throw e}return v}
 tx(stores,fn){return new Promise((resolve,reject)=>{let tx=this.db.transaction(stores,'readwrite');try{fn(tx)}catch(e){tx.abort();reject(e)}tx.oncomplete=()=>resolve();tx.onabort=tx.onerror=()=>reject(tx.error||new Error('Could not save on this device'))})}
 writeLocal(op){if(!this.db)return Promise.reject(Error('Storage not ready'));return this.tx(['operations','outbox'],tx=>{tx.objectStore('operations').put(op);tx.objectStore('outbox').put(op)})}
 async pull(){let more=true;while(more){let data=await this.api('sync?since='+this.cursor);if(data.operations.length){let cursor=data.operations.at(-1).seq;await this.tx(['operations','meta'],tx=>{data.operations.forEach(row=>tx.objectStore('operations').put(row.op));tx.objectStore('meta').put(cursor,'cursor')});this.replica.import(data.operations.map(row=>row.op));this.cursor=cursor}more=data.more}}
 async flush(){if(this.busy||!this.ready||this.stopped)return;this.busy=true;try{await this.queuePersistence();while(this.pending.size){await this.queuePersistence();let batch=[],bytes=0;for(let op of this.pending.values()){let size=JSON.stringify(op).length;if(batch.length&&(batch.length>=100||bytes+size>600000))break;batch.push(op);bytes+=size}let {accepted}=await this.api('sync',{method:'POST',body:JSON.stringify({operations:batch})});await this.tx(['outbox'],tx=>accepted.forEach(id=>tx.objectStore('outbox').delete(id)));accepted.forEach(id=>this.pending.delete(id));}await this.pull();this.onStatus('All changes saved')}catch(e){this.lastError=e;if(this.unpersisted.size)this.onStatus('Device storage error — keep this tab open');else if(e.status===403||e.status===401)this.onStatus('Access changed — export unsynced work');else if(e.status>=400&&e.status<500)this.onStatus('Sync error — '+e.message);else this.onStatus('Offline · edits saved on this device')}finally{this.busy=false}}
 tick(){if(this.stopped)return;setTimeout(async()=>{await this.flush();this.tick()},document.hidden?7000:1400)}
 async upload(file){if(file.size>10*1024*1024)throw Error('Files must be smaller than 10 MB');return this.api('assets',{method:'POST',body:file,headers:{'content-type':file.type||'application/octet-stream','x-file-name':encodeURIComponent(file.name)}})}
}
